
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Для генерации Prisma Client не требуется реальное подключение к БД
    // Используем фиктивный URL если DATABASE_URL не установлен (например, при npm ci)
    // Реальное подключение будет использоваться из .env во время выполнения
    url: process.env.DATABASE_URL || "postgresql://user:password@localhost:5432/db",
  },
});
