// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Функция для получения URL базы данных
// Приоритет: публичный URL (для миграций во время build) > внутренний URL > fallback
function getDatabaseUrl(): string {
  // Публичный URL доступен во время build на Railway
  if (process.env.DATABASE_PUBLIC_URL) {
    return process.env.DATABASE_PUBLIC_URL;
  }
  // Внутренний URL для runtime
  if (process.env.DATABASE_URL) {
    return process.env.DATABASE_URL;
  }
  // Fallback для генерации клиента без БД
  return "postgresql://user:password@localhost:5432/db";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: getDatabaseUrl(),
  },
});
